export const Project = [{
        id: 1,
        name: 'Crud MERN STACK',
        tech: 'React , Node.JS , Mongodb , Express , Bootstrap',
        desc: 'One of my first web project that i build to understand how to work with a database and also to up my skills with React',
        img: 'photo',
        url: 'gitlink',
    },
    {
        id: 2,
        name: 'Quizz App',
        tech: 'Symfony,JS',
        desc: 'I work on this application with 3 mates, i made only the backend on this one cause i was training my Symfony skills',
        img: '',
        url: '',
    },
    {
        id: 3,
        name: 'EvolCiv website',
        tech: 'react,bootstrap,nodejs',
        desc: 'I made a website for my future game so i can post on this one many news about it. Also a referring place to support or the wiki.',
        img: '',
        url: '',
    },
    {
        id: 4,
        name: 'EvolCiv',
        tech: 'C-Sharp',
        desc: 'My first game, a survival typed game but with some special features like civilisation, evolution through era and more to come !',
        img: '',
        url: '',
    },
    {
        id: 5,
        name: 'EvolCiv',
        tech: 'C-Sharp',
        desc: 'My first game, a survival typed game but with some special features like civilisation, evolution through era and more to come !',
        img: '',
        url: '',
    },
    {
        id: 6,
        name: 'EvolCiv',
        tech: 'C-Sharp',
        desc: 'My first game, a survival typed game but with some special features like civilisation, evolution through era and more to come !',
        img: '',
        url: '',
    },
    {
        id: 7,
        name: 'EvolCiv',
        tech: 'C-Sharp',
        desc: 'My first game, a survival typed game but with some special features like civilisation, evolution through era and more to come !',
        img: '',
        url: '',
    },
    {
        id: 8,
        name: 'EvolCiv',
        tech: 'C-Sharp',
        desc: 'My first game, a survival typed game but with some special features like civilisation, evolution through era and more to come !',
        img: '',
        url: '',
    },
]